### ISSUE TITLE
LT登壇者の取得について

### ISSUE THREAD

**Issue by Cyndaquil1999** [Cyndaquil1999/LT-Support-Tool#1]
API等の動作チェックを兼ねてPythonでスクレイピングをできるようにしました（Scraping.py）

しかしながらアプリをJavaScriptで動かす都合上、スクレイピングをするならJavaScriptに移植するか、登壇者情報は手入力にするかのいずれかが良いかと思います。どうしましょう。

**Comment by Cyndaquil1999** [comment]
あ

**Comment by Cyndaquil1999** [comment]
test

**Comment by Cyndaquil1999** [comment]
test

**Comment by Cyndaquil1999** [comment]
WebHook動作確認

**Comment by henacken** [comment]
Javascriptの方挑戦してみたいです。。。

**Comment by Cyndaquil1999** [comment]
それでは、既にあるScraping.pyをJavaScriptに移植する形でお願いします～

**Comment by Cyndaquil1999** [comment]
コチラいかがですか

**Comment by henacken** [comment]
わかりました！技術的に分からない所があったらその都度聞きます！
