### ISSUE TITLE
実装方針について

### ISSUE THREAD

**Issue by Cyndaquil1999** [Cyndaquil1999/LT-Support-Tool#2]
以下の技術にて実装しようかと思いますがいかがでしょうか

### フロントエンド
- React or Vue？

### バックエンド
- Node.js

### デプロイ
- Deno Deploy

**Comment by Cyndaquil1999** [comment]
今回はLT会の支援ツールなので、レスポンシブデザインは特段配慮せず、PCで閲覧した際に良いUIかどうかわかればよいかなと思う...。（タブレット仕様のUI実装しても良いけどPCみんな持参してくるよねという思想）

**Comment by henacken** [comment]
そうですね、PCだけでよいと思います。
