### ISSUE TITLE
担当箇所の割り当て

### ISSUE THREAD

**Issue by Cyndaquil1999** [Cyndaquil1999/LT-Support-Tool#4]
## フロント
- [x]  タイマーの実装
- [x] コメント欄の実装 
- [x] 発表者リストの実装

## バックエンド
- [x]  登壇者情報の収集
- [x] タイマー機能の実装
- [x] コメント欄の実装

**Comment by Cyndaquil1999** [comment]
コメント欄の実装やります

**Comment by henacken** [comment]
タイマーの機能の実装やります！

**Comment by Cyndaquil1999** [comment]
基本的なコメント欄の実装終わったので、発表者リストの表示やります

**Comment by Cyndaquil1999** [comment]
発表者リスト完了

**Comment by henacken** [comment]
基本的なタイマー機能は実装できました。

**Comment by henacken** [comment]
タイマー機能の機能およびデザイン終わりました～
